Fix wamv_locked parameter name
osrf/vrx-docker pull request #49
Opened 2022-03-29 14:12 UTC by caguero

When launching a task, we were passing `robot_locked` instead of `wamv_locked`.

2022-03-29 16:08 UTC, M1chaelM commented
I want to make sure we document the deeper issue here, which is that vrx-docker was also used for VORC, so @mabelzhang renamed this parameter to make it more generic (VORC does not use a WAMV). I believe fixing it this way for VRX will break VORC. In the short term, we may want to do this but eventually we should probably use `robot_locked` for both.

2022-03-30 00:34 UTC, M1chaelM commented
This is not that easy to test, but I think I'm still seeing the problem. 
* I rebuilt the server image with your modified script.
* I logged in to it to verify that the script was changed.
* I built a version of our example team that tries to move forward during the perception tag and uploaded it to Dockerhub at `virtualrobotx/vrx_2022_simple:perception`. 
* I made 3 `team_config` files for this image and called the team `TEAM=vrx_2022_simple`
* I used `./run_trial.bash -n $TEAM perception 0` to run the trial.
* While it was running I again logged in to it to verify it was using the `wamv_locked` variable.
* When I replay with `./replay_trial.bash -n $TEAM perception 0` the WAMV still drives over the obstacles and off into the sunset.

2022-03-30 00:42 UTC, M1chaelM requested changes
See above... still getting the same problem. Could you try testing it using the `run_trial.bash` script to see whether you can reproduce it?

2022-03-30 21:43 UTC, caguero commented
> See above... still getting the same problem. Could you try testing it using the `run_trial.bash` script to see whether you can reproduce it?

Sure, I'll test it and report back. Thanks for testing!

2022-04-01 22:59 UTC, M1chaelM commented
I posted the modified `basic_node.py` for testing purposes. This should probably be changed back before we merge.

2022-04-08 20:56 UTC, M1chaelM commented
Per discussion in https://github.com/osrf/vrx/pull/446, it seems that the `wamv_locked` parameter is completely ignored anyway when we override the `urdf` argument because it means we will not generate the `urdf` on the fly from a `xacro`. To resolve this issue, we need to build the `urdf` in a pre-locked state. 

We added this option to `generate_wamv.launch` in https://github.com/osrf/vrx/pull/446, so [e2451ad](https://github.com/osrf/vrx-docker/pull/49/commits/e2451ad5fe42b3a23c9f6a42d6f287ced72d04f6) updates `prepare_team_wamv.bash` script to use it. This should resolve the problem for now but it will mean that `urdf`s generated with this script can effectively only be used in the competition where there is a scoring plugin to unlock them.

2022-04-08 21:08 UTC, M1chaelM commented
Side note: amusingly, the perception task still sort of works when you are driving because the objects are always spawned in positions relative to the wamv. It's much harder, but still kind of interesting.

2022-04-08 21:38 UTC, M1chaelM commented
This should now be fixed. To test, make sure you've generated at least `perception0.world` and run:
```
TEAM=test_perception_lock
TASK=perception
TRIAL=0
cd ~/vrx_ws/src/vrx-docker/team_config
mkdir $TEAM
cp -v example_team/* $TEAM/
echo "virtualrobotx/vrx_2022_simple:perception" > $TEAM/dockerhub_image.txt
cd ../
./prepare_team_wamv.bash $TEAM
./run_trial.bash -n $TEAM $TASK $TRIAL
```
When it's finished run
```
./replay_trial.bash -n $TEAM $TASK $TRIAL
```
and verify that the wamv does not move.

2022-04-08 21:39 UTC, M1chaelM approved these changes
I approve but since I've taken over the changes to this PR I think it would be good if you could test also, @caguero . Thanks!

2022-04-10 20:58 UTC, M1chaelM commented
@caguero I decided it would be better to merge this since we are very close to the competition now.

2022-04-10 20:59 UTC, merged