Rename 2023 mwe folder
osrf/vrx-docker pull request #72
Opened 2023-08-18 13:24 UTC by M1chaelM

This very minor change is intended to make the file path for the 2023 MWE consistent with the name we used in 2022, as discussed in this issue: https://github.com/osrf/vrx/issues/719 . This will make it easier to update the tutorial (discussed in the same issue).

2023-08-18 13:50 UTC, M1chaelM commented
On closer inspection of the tutorial and state of the repository, I'm converting this PR to a draft so I can address a few more things:
* [ ] It would be better to rename the image we have here to "simple" instead of starter, since it is closer to the image we called "simple" for VRX 2022.
* [ ] We should also add an analog to the VRX 2022 starter image with a readme explaining how to use it. The reason is to give an example of how to build a workspace and set up a development environment in the container, and this is a little more complicated.
* [ ] The [README](https://github.com/osrf/vrx-docker/blob/master/mwes/README.md) for the MWE directory as a whole needs to be updated.

2023-08-29 21:02 UTC, caguero requested changes
The instructions worked for me and I was able to run the solution and verify that the boat moves.

I just left a few minor comments.

2023-08-29 21:02 UTC, caguero requested changes
The instructions worked for me and I was able to run the solution and verify that the boat moves.

I just left a few minor comments.

2023-08-30 13:34 UTC, M1chaelM commented on mwes/2023/vrx_2023_starter/Dockerfile
> +# Set Ubuntu release
This is done in the base image.

2023-08-30 13:35 UTC, M1chaelM commented on mwes/2023/vrx_2023_starter/Dockerfile
> +# Set up a catkin workspace
```suggestion
# Set up a colcon workspace
```

2023-08-30 13:48 UTC, caguero commented on mwes/2023/vrx_2023_starter/Dockerfile
> +# Here we use my_vrx as an example of a source code repository stored
`my_source` instead of `my_vrx`?

2023-08-31 14:45 UTC, caguero approved these changes

2023-09-01 18:44 UTC, merged